services:
  jenkins-dind:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins-home
    expose:
      - 2376
    networks:
      jenkins:
        aliases:
          - docker

  jenkins-blueocean:
    build: .
    restart: on-failure
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - jenkins

networks:
  jenkins:

volumes:
  jenkins-docker-certs:
    driver: local
  jenkins-data:
    driver: local
